# Generated by Django 5.2.7 on 2025-11-03 01:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partitura',
            fields=[
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('autor', models.CharField(max_length=80)),
                ('arreglista', models.CharField(blank=True, max_length=80)),
                ('archivo', models.FileField(upload_to='scoresheets/')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
