# Generated by Django 5.2.7 on 2025-11-03 01:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nivel', models.CharField(choices=[('Inicial', 'inicial'), ('Intermedio', 'intermedio'), ('Avanzado', 'avanzado')], default=('Inicial', 'inicial'), max_length=16)),
                ('horas_catedra', models.IntegerField(default=20)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
