# Generated by Django 5.2.7 on 2025-11-01 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nivel', models.CharField(choices=[('n1', 'inicial'), ('n2', 'intermedio'), ('n3', 'avanzado')], default=('n1', 'inicial'), max_length=2)),
                ('horas_catedra', models.IntegerField(default=80)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
