# Generated by Django 5.2.7 on 2025-11-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nivel',
            field=models.CharField(choices=[('Nivel Inicial', 'inicial'), ('Nivel Intermedio', 'intermedio'), ('Nivel avanzado', 'avanzado')], default=('Nivel Inicial', 'inicial'), max_length=16),
        ),
    ]
