# Generated by Django 5.2.7 on 2025-11-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_asignatura_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nivel',
            field=models.CharField(choices=[('Inicial', 'inicial'), ('Intermedio', 'intermedio'), ('Avanzado', 'avanzado')], default=('Inicial', 'inicial'), max_length=16),
        ),
    ]
