# Generated by Django 5.2.7 on 2025-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_asignatura_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='horas_catedra',
            field=models.IntegerField(default=20),
        ),
    ]
