# Generated by Django 5.2.7 on 2025-11-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
