# Generated by Django 5.2.7 on 2025-11-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuario', '0002_usuario_descripcion_usuario_sitio_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
