# Generated by Django 5.2.7 on 2025-11-04 06:00

import cuentas_usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuario', '0003_alter_usuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='default/avatar_black.jpg', null=True, upload_to=cuentas_usuario.models.avatar_upload_to, verbose_name='Avatar'),
        ),
    ]
